### ISSUE TITLE
Error on calling lspimport.import

### ISSUE THREAD

**Issue by olzhasar** [stevanmilic/nvim-lspimport#4]
Hi,
Thank you for the interesting package.

I am trying to get it work, but I am constantly receiving and error:

```
Error executing vim.schedule lua callback: ...lar/neovim/0.9.5/share/nvim/runtime/lua/vim/lsp/util.lua:393: text_edits: expected table, got nil                             
stack traceback:                                                                                                                                                            
        [C]: in function 'error'                                                                                                                                            
        vim/shared.lua: in function 'validate'                                                                                                                              
        ...lar/neovim/0.9.5/share/nvim/runtime/lua/vim/lsp/util.lua:393: in function 'apply_text_edits'                                                                     
        .../pack/packer/start/nvim-lspimport/lua/lspimport/init.lua:62: in function 'resolve_import'                                                                        
        .../pack/packer/start/nvim-lspimport/lua/lspimport/init.lua:84: in function 'lsp_completion_handler'                                                                
        .../pack/packer/start/nvim-lspimport/lua/lspimport/init.lua:118: in function 'handler'                                                                              
        ...w/Cellar/neovim/0.9.5/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''                                                                                    
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Neovim version: 0.9.5

**Comment by stevanmilic** [comment]
@olzhasar that's strange, what `pyright` version are you using? 

I've made a commit https://github.com/stevanmilic/nvim-lspimport/commit/1a8c841715f877e6aeb1e9646331390e87109c69 to ensure text edits exist in LSP response in order to try and resolve an import

**Comment by olzhasar** [comment]
@stevanmilic
Sorry for the late reply,
My `pyright` version is 1.1.351.
The above mentioned error disappeared after your changes. However, auto import still doesn't work. Whenever I invoke the command it outputs: "no unresolved import error", even though lsp highlights the word as `X is not defined`

I use `null-ls` alongside `pyright` btw if that helps

**Comment by stevanmilic** [comment]
@olzhasar do you get _any_ auto imports, or you're getting that message for _some_ of the undefined terms? Does pyright provide completion for those terms?

**Comment by olzhasar** [comment]
@stevanmilic I don't think I got any auto imports so far. Pyright does indeed provided completions for things I was trying to auto-import and, they were loaded in the workspace according to how pyright works, e.g. opened in some other buffer.
